"""Cross-validation tests comparing stats-cli against R reference values.

R is the gold standard for statistical computing. JMP uses SAS internally,
which produces results equivalent to R for standard algorithms.
If stats-cli matches R, it matches JMP.

Reference values generated by: r_scripts/generate_reference.R
"""

import json
import os

from stats_engine.anova import anova
from stats_engine.capability import capability
from stats_engine.correlation import correlation
from stats_engine.descriptive import descriptive
from stats_engine.homogeneity import homogeneity
from stats_engine.multiple_comparison import multiple_comparison
from stats_engine.nonparametric import nonparametric
from stats_engine.normality import normality
from stats_engine.regression import regression
from stats_engine.ttest import ttest

# Load R reference values
REF_PATH = os.path.join(os.path.dirname(__file__), "reference_values.json")
with open(REF_PATH, encoding="utf-8") as f:
    REF = json.load(f)


# Tolerance helpers
def assert_close(actual, expected, abs_tol=1e-6, rel_tol=1e-4, label=""):
    """Assert two floats are close within tolerance."""
    if expected == 0:
        assert abs(actual) < abs_tol, f"{label}: got {actual}, expected ~0 (abs_tol={abs_tol})"
    else:
        diff = abs(actual - expected)
        rel = diff / abs(expected)
        assert diff < abs_tol or rel < rel_tol, (
            f"{label}: got {actual}, expected {expected} (abs_diff={diff:.2e}, rel_diff={rel:.2e})"
        )


def assert_same_conclusion(actual_p, expected_p, alpha=0.05):
    """Assert both p-values lead to the same significance conclusion."""
    actual_sig = actual_p < alpha
    expected_sig = expected_p < alpha
    assert actual_sig == expected_sig, (
        f"Conclusion mismatch: p={actual_p:.6f} ({'sig' if actual_sig else 'ns'}) "
        f"vs p={expected_p:.6f} ({'sig' if expected_sig else 'ns'})"
    )


# Iris data
IRIS_DATA = {
    "setosa_sl": [
        5.1,
        4.9,
        4.7,
        4.6,
        5.0,
        5.4,
        4.6,
        5.0,
        4.4,
        4.9,
        5.4,
        4.8,
        4.8,
        4.3,
        5.8,
        5.7,
        5.4,
        5.1,
        5.7,
        5.1,
        5.4,
        5.1,
        4.6,
        5.1,
        4.8,
        5.0,
        5.0,
        5.2,
        5.2,
        4.7,
        4.8,
        5.4,
        5.2,
        5.5,
        4.9,
        5.0,
        5.5,
        4.9,
        4.4,
        5.1,
        5.0,
        4.5,
        4.4,
        5.0,
        5.1,
        4.8,
        5.1,
        4.6,
        5.3,
        5.0,
    ],
    "versicolor_sl": [
        7.0,
        6.4,
        6.9,
        5.5,
        6.5,
        5.7,
        6.3,
        4.9,
        6.6,
        5.2,
        5.0,
        5.9,
        6.0,
        6.1,
        5.6,
        6.7,
        5.6,
        5.8,
        6.2,
        5.6,
        5.9,
        6.1,
        6.3,
        6.1,
        6.4,
        6.6,
        6.8,
        6.7,
        6.0,
        5.7,
        5.5,
        5.5,
        5.8,
        6.0,
        5.4,
        6.0,
        6.7,
        6.3,
        5.6,
        5.5,
        5.5,
        6.1,
        5.8,
        5.0,
        5.6,
        5.7,
        5.7,
        6.2,
        5.1,
        5.7,
    ],
    "virginica_sl": [
        6.3,
        5.8,
        7.1,
        6.3,
        6.5,
        7.6,
        4.9,
        7.3,
        6.7,
        7.2,
        6.5,
        6.4,
        6.8,
        5.7,
        5.8,
        6.4,
        6.5,
        7.7,
        7.7,
        6.0,
        6.9,
        5.6,
        7.7,
        6.3,
        6.7,
        7.2,
        6.2,
        6.1,
        6.4,
        7.2,
        7.4,
        7.9,
        6.4,
        6.3,
        6.1,
        7.7,
        6.3,
        6.4,
        6.0,
        6.9,
        6.7,
        6.9,
        5.8,
        6.8,
        6.7,
        6.7,
        6.3,
        6.5,
        6.2,
        5.9,
    ],
}


class TestDescriptive:
    """Cross-validate descriptive statistics against R."""

    def test_iris_setosa_descriptive(self):
        r = descriptive(values=IRIS_DATA["setosa_sl"])
        ref = REF["descriptive_iris_setosa"]

        assert r["n"] == ref["n"]
        assert_close(r["mean"], ref["mean"], abs_tol=1e-10)
        assert_close(r["std"], ref["sd"], abs_tol=1e-10)
        assert_close(r["median"], ref["median"], abs_tol=1e-10)
        assert_close(r["min"], ref["min"], abs_tol=1e-10)
        assert_close(r["max"], ref["max"], abs_tol=1e-10)
        assert_close(r["q1"], ref["q1"], abs_tol=1e-10)
        assert_close(r["q3"], ref["q3"], abs_tol=1e-10)


class TestNormality:
    """Cross-validate normality tests against R."""

    def test_shapiro_wilk(self):
        r = normality(values=IRIS_DATA["setosa_sl"])
        ref = REF["normality_iris_setosa"]

        assert_close(r["shapiro_wilk"]["statistic"], ref["shapiro_w"], abs_tol=1e-4)
        assert_close(r["shapiro_wilk"]["p_value"], ref["shapiro_p"], abs_tol=1e-2)


class TestTTest:
    """Cross-validate t-tests against R."""

    def test_one_sample(self):
        r = ttest(test_type="one_sample", values=IRIS_DATA["setosa_sl"], mu=5.0)
        ref = REF["ttest_one_sample"]

        assert_close(r["t_statistic"], ref["t_stat"], abs_tol=1e-6)
        assert_close(r["p_value"], ref["p_value"], abs_tol=1e-4)
        assert_close(r["ci_95"][0], ref["ci_lower"], abs_tol=1e-3)
        assert_close(r["ci_95"][1], ref["ci_upper"], abs_tol=1e-3)
        assert r["n"] == 50

    def test_two_sample_welch(self):
        r = ttest(
            test_type="two_sample",
            values=IRIS_DATA["setosa_sl"],
            values2=IRIS_DATA["versicolor_sl"],
        )
        ref = REF["ttest_two_sample_welch"]

        assert_close(r["t_statistic"], ref["t_stat"], abs_tol=1e-6)
        assert_close(r["p_value"], ref["p_value"], abs_tol=1e-10)
        assert_close(r["mean_difference"], ref["mean_diff"], abs_tol=1e-6)

    def test_paired(self):
        before = [85, 88, 90, 82, 87, 91, 86, 89, 84, 88]
        after = [88, 91, 93, 86, 90, 95, 89, 92, 87, 91]
        r = ttest(test_type="paired", values=before, values2=after)
        ref = REF["ttest_paired"]

        assert_close(r["t_statistic"], ref["t_stat"], abs_tol=1e-6)
        assert_close(r["p_value"], ref["p_value"], abs_tol=1e-6)
        assert_close(r["ci_95"][0], ref["ci_lower"], abs_tol=1e-3)
        assert_close(r["ci_95"][1], ref["ci_upper"], abs_tol=1e-3)


class TestANOVA:
    """Cross-validate ANOVA against R."""

    def test_one_way_iris(self):
        groups = [IRIS_DATA["setosa_sl"], IRIS_DATA["versicolor_sl"], IRIS_DATA["virginica_sl"]]
        r = anova(groups=groups, anova_type="one_way")
        ref = REF["anova_one_way"]

        assert_close(r["f_statistic"], ref["f_stat"], abs_tol=1e-6)
        assert_close(r["p_value"], ref["p_value"], abs_tol=1e-20)
        assert r["df_between"] == ref["df_between"]
        assert r["df_within"] == ref["df_within"]
        assert_close(r["ss_between"], ref["ss_between"], abs_tol=1e-6)
        assert_close(r["ss_within"], ref["ss_within"], abs_tol=1e-6)
        assert_close(r["ms_between"], ref["ms_between"], abs_tol=1e-6)
        assert_close(r["ms_within"], ref["ms_within"], abs_tol=1e-6)
        assert_close(r["eta_squared"], ref["eta_squared"], abs_tol=1e-4)


class TestRegression:
    """Cross-validate regression against R."""

    def test_linear_anscombe(self):
        x = [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5]
        y = [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]
        r = regression(x=x, y=y, reg_type="linear")
        ref = REF["regression_linear"]

        assert_close(r["coefficients"]["slope"], ref["slope"], abs_tol=1e-8)
        assert_close(r["coefficients"]["intercept"], ref["intercept"], abs_tol=1e-8)
        assert_close(r["r_squared"], ref["r_squared"], abs_tol=1e-6)


class TestCorrelation:
    """Cross-validate correlation against R."""

    def test_pearson(self):
        r = correlation(
            x=IRIS_DATA["setosa_sl"],
            y=IRIS_DATA["versicolor_sl"],
            method="pearson",
        )
        ref = REF["correlation_pearson"]

        assert_close(r["correlation"], ref["r_value"], abs_tol=1e-8)
        assert_close(r["p_value"], ref["p_value"], abs_tol=1e-4)

    def test_spearman(self):
        r = correlation(
            x=IRIS_DATA["setosa_sl"],
            y=IRIS_DATA["versicolor_sl"],
            method="spearman",
        )
        ref = REF["correlation_spearman"]

        assert_close(r["correlation"], ref["rho"], abs_tol=1e-4)


class TestNonparametric:
    """Cross-validate non-parametric tests against R."""

    def test_mann_whitney(self):
        g1 = [23, 25, 28, 30, 32, 35, 27, 29]
        g2 = [31, 33, 36, 38, 40, 42, 35, 37]
        r = nonparametric(test_type="mann_whitney", x=g1, y=g2)
        ref = REF["mann_whitney"]

        assert_same_conclusion(r["p_value"], ref["p_value"])

    def test_kruskal_wallis(self):
        g1 = [7, 14, 14, 13, 12, 9, 6, 14, 12, 7]
        g2 = [15, 17, 13, 15, 15, 13, 9, 12, 10, 6]
        g3 = [6, 7, 11, 8, 7, 6, 10, 5, 4, 9]
        r = nonparametric(test_type="kruskal_wallis", groups=[g1, g2, g3])
        ref = REF["kruskal_wallis"]

        assert_close(r["h_statistic"], ref["chi2_stat"], abs_tol=1e-4)
        assert_same_conclusion(r["p_value"], ref["p_value"])

    def test_wilcoxon_signed_rank(self):
        x = [1.83, 0.50, 1.62, 2.48, 1.68, 1.88, 1.55, 3.06, 1.30]
        y = [0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29]
        r = nonparametric(test_type="wilcoxon", x=x, y=y)
        ref = REF["wilcoxon_signed_rank"]

        assert_same_conclusion(r["p_value"], ref["p_value"])

    def test_chi_square(self):
        contingency = [[50, 30], [20, 60]]
        r = nonparametric(test_type="chi_square", observed=contingency)
        ref = REF["chi_square"]

        assert_close(r["chi2_statistic"], ref["chi2_stat"], abs_tol=1e-4)
        assert_same_conclusion(r["p_value"], ref["p_value"])
        assert r["df"] == ref["df"]


class TestHomogeneity:
    """Cross-validate homogeneity tests against R."""

    def test_levene(self):
        r = homogeneity(
            test_type="levene",
            groups=[IRIS_DATA["setosa_sl"], IRIS_DATA["versicolor_sl"], IRIS_DATA["virginica_sl"]],
        )
        ref = REF["levene_test"]

        assert_close(r["statistic"], ref["f_stat"], abs_tol=1e-2)
        assert_same_conclusion(r["p_value"], ref["p_value"])

    def test_bartlett(self):
        r = homogeneity(
            test_type="bartlett",
            groups=[IRIS_DATA["setosa_sl"], IRIS_DATA["versicolor_sl"], IRIS_DATA["virginica_sl"]],
        )
        ref = REF["bartlett_test"]

        assert_close(r["statistic"], ref["chi2_stat"], abs_tol=1e-2)
        assert_same_conclusion(r["p_value"], ref["p_value"])


class TestMultipleComparison:
    """Cross-validate multiple comparison against R."""

    def test_tukey_hsd(self):
        groups = [IRIS_DATA["setosa_sl"], IRIS_DATA["versicolor_sl"], IRIS_DATA["virginica_sl"]]
        r = multiple_comparison(test_type="tukey", groups=groups)
        ref = REF["tukey_hsd"]

        # Map group indices to names
        group_names = ["setosa", "versicolor", "virginica"]
        for pair_name, ref_vals in ref.items():
            # Find matching pair in our results
            our_pair = None
            for pair in r["comparisons"]:
                name_i = group_names[pair["group_i"]]
                name_j = group_names[pair["group_j"]]
                key = f"{name_j}-{name_i}"
                if key == pair_name:
                    our_pair = pair
                    break
            assert our_pair is not None, f"Pair {pair_name} not found in results"
            # Mean diff may differ in sign depending on subtraction order
            assert_close(abs(our_pair["mean_diff"]), abs(ref_vals["diff"]), abs_tol=1e-6)
            assert_close(our_pair["p_value"], ref_vals["p_adj"], rel_tol=0.01)


class TestCapability:
    """Cross-validate process capability against R."""

    def test_capability(self):
        cap_data = [
            10.1,
            9.8,
            10.2,
            9.9,
            10.0,
            10.1,
            9.7,
            10.3,
            10.0,
            9.9,
            10.2,
            10.1,
            9.8,
            10.0,
            10.1,
            9.9,
            10.2,
            10.0,
            10.1,
            9.8,
        ]
        r = capability(values=cap_data, usl=11.0, lsl=9.0)
        ref = REF["process_capability"]

        assert_close(r["mean"], ref["mean"], abs_tol=1e-10)
        assert_close(r["std_overall"], ref["sd_overall"], abs_tol=1e-8)
        # Pp/Ppk use overall std (same formula in both)
        assert_close(r["pp"], ref["pp"], rel_tol=0.01)
        assert_close(r["ppk"], ref["ppk"], rel_tol=0.01)
        # Cp/Cpk use within-subgroup std (moving range)
        assert_close(r["cp"], ref["cp"], rel_tol=0.01)
        assert_close(r["cpk"], ref["cpk"], rel_tol=0.01)
