"""Command discovery metadata for AI agents."""

COMMANDS = {
    "explore": {
        "description": "Explore data file structure: columns, types, missing values, basic stats",
        "category": "data",
        "input": ["file", "sheet", "rows"],
        "output_fields": ["n_rows", "n_columns", "columns", "numeric_columns", "sample_data"],
        "example": '{"command": "explore", "params": {"file": "data.xlsx"}}',
    },
    "descriptive": {
        "description": "Descriptive statistics: mean, median, SD, RSD%, range, quartiles, 95% CI",
        "category": "basic",
        "input": ["values"],
        "output_fields": [
            "n",
            "mean",
            "median",
            "std",
            "rsd_percent",
            "min",
            "max",
            "range",
            "q1",
            "q3",
            "iqr",
            "ci_95_lower",
            "ci_95_upper",
            "skewness",
            "kurtosis",
        ],
        "example": '{"command": "descriptive", "params": {"values": [10.2, 10.5, 10.3]}}',
    },
    "normality": {
        "description": "Normality tests: Shapiro-Wilk, Anderson-Darling, Lilliefors",
        "category": "basic",
        "input": ["values"],
        "output_fields": ["shapiro_wilk", "anderson_darling", "lilliefors", "is_normal"],
        "example": '{"command": "normality", "params": {"values": [10.2, 10.5, 10.3]}}',
    },
    "capability": {
        "description": "Process capability: Cp, Cpk, Pp, Ppk, Cpm, confidence intervals",
        "category": "spc",
        "input": ["values", "usl", "lsl", "target"],
        "output_fields": [
            "cp",
            "cpk",
            "pp",
            "ppk",
            "cpm",
            "cp_ci_lower",
            "cp_ci_upper",
            "cpk_ci_lower",
            "cpk_ci_upper",
            "rating",
            "performance",
        ],
        "example": '{"command": "capability", "params": {"values": [...], "usl": 11.0, "lsl": 9.0}}',
    },
    "control_chart": {
        "description": "Control charts: xbar, r, imr, p, np, c, u, ewma, cusum",
        "category": "spc",
        "input": ["values", "chart_type", "subgroup_size"],
        "output_fields": ["chart_type", "center", "ucl", "lcl", "points", "out_of_control_points", "summary"],
        "example": '{"command": "control_chart", "params": {"chart_type": "imr", "values": [...]}}',
    },
    "ttest": {
        "description": "t-tests: one_sample, two_sample, paired",
        "category": "hypothesis",
        "input": ["test_type", "values", "values2", "mu"],
        "output_fields": ["test_type", "t_statistic", "p_value", "significant", "ci_95"],
        "example": '{"command": "ttest", "params": {"test_type": "two_sample", "values": [10.2, 10.5], "values2": [11.3, 11.5]}}',
    },
    "anova": {
        "description": "ANOVA: one_way, two_way",
        "category": "hypothesis",
        "input": ["anova_type", "groups", "alpha", "data"],
        "output_fields": ["anova_type", "f_statistic", "p_value", "significant", "eta_squared", "omega_squared", "df_between", "df_within", "ss_between", "ss_within", "ms_between", "ms_within"],
        "example": '{"command": "anova", "params": {"anova_type": "one_way", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "regression": {
        "description": "Regression: linear, quadratic, polynomial, multiple, stepwise, logistic, exponential, power, logarithmic, sigmoid",
        "category": "regression",
        "input": ["x", "y", "reg_type", "degree", "file", "x_columns", "y_column", "alpha"],
        "output_fields": ["regression_type", "r_squared", "adj_r_squared", "coefficients", "f_statistic", "p_value"],
        "example": '{"command": "regression", "params": {"x": [1, 2, 3], "y": [2, 4, 6]}}',
    },
    "correlation": {
        "description": "Correlation: pearson, spearman, kendall",
        "category": "regression",
        "input": ["x", "y", "method"],
        "output_fields": ["method", "correlation", "p_value", "r_squared"],
        "example": '{"command": "correlation", "params": {"x": [1, 2, 3], "y": [2, 4, 6]}}',
    },
    "nonparametric": {
        "description": "Non-parametric tests: mann_whitney, kruskal_wallis, wilcoxon, chi_square, friedman",
        "category": "hypothesis",
        "input": ["test_type", "x", "y", "groups", "observed"],
        "output_fields": ["test_type", "statistic", "p_value", "significant"],
        "example": '{"command": "nonparametric", "params": {"test_type": "mann_whitney", "x": [10.2, 10.5], "y": [11.3, 11.5]}}',
    },
    "homogeneity": {
        "description": "Homogeneity of variance: levene, bartlett",
        "category": "hypothesis",
        "input": ["test_type", "groups"],
        "output_fields": ["test_type", "statistic", "p_value", "significant"],
        "example": '{"command": "homogeneity", "params": {"test_type": "levene", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "multiple_comparison": {
        "description": "Multiple comparison: tukey, bonferroni, scheffe",
        "category": "hypothesis",
        "input": ["test_type", "groups", "alpha"],
        "output_fields": ["test_type", "comparisons", "significant_pairs"],
        "example": '{"command": "multiple_comparison", "params": {"test_type": "tukey", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "equivalence": {
        "description": "Equivalence tests: tost, one_sample_tost",
        "category": "hypothesis",
        "input": ["test_type", "values", "values2", "mu", "delta"],
        "output_fields": ["test_type", "t_statistic", "p_value", "equivalent", "ci_90"],
        "example": '{"command": "equivalence", "params": {"test_type": "tost", "values": [10.2, 10.5], "values2": [10.3, 10.6], "delta": 0.5}}',
    },
    "outlier": {
        "description": "Outlier detection: grubbs, dixon, iqr, zscore",
        "category": "basic",
        "input": ["values", "method", "alpha"],
        "output_fields": ["method", "outliers", "n_outliers", "clean_data"],
        "example": '{"command": "outlier", "params": {"values": [...], "method": "grubbs"}}',
    },
    "trend": {
        "description": "Trend analysis: cusum, ewma, runs",
        "category": "spc",
        "input": ["values", "test_type", "target"],
        "output_fields": ["test_type", "alarm_points", "stable"],
        "example": '{"command": "trend", "params": {"values": [...], "test_type": "cusum"}}',
    },
    "doe": {
        "description": "Design of Experiments: full_factorial, fractional_factorial, response_surface, taguchi",
        "category": "doe",
        "input": ["doe_type", "factors"],
        "output_fields": ["doe_type", "design_matrix", "n_runs"],
        "example": '{"command": "doe", "params": {"doe_type": "full_factorial", "factors": [{"name": "Temp", "levels": 3}, {"name": "Time", "levels": 2}]}}',
    },
    "gage_rr": {
        "description": "MSA/Gage R&R: crossed, nested, attribute, bias, linearity, stability",
        "category": "msa",
        "input": ["analysis_type", "measurements", "parts", "operators", "tolerance"],
        "output_fields": ["analysis_type", "variance_components", "contribution", "study_variation", "ndc", "rating"],
        "example": '{"command": "gage_rr", "params": {"analysis_type": "crossed", "measurements": [...], "parts": [...], "operators": [...]}}',
    },
    "reliability": {
        "description": "Reliability and survival analysis: weibull, kaplan_meier, distribution, stability",
        "category": "reliability",
        "input": ["analysis_type", "times", "status", "values"],
        "output_fields": ["parameters", "b_lives", "mttf", "shelf_life"],
        "example": '{"command": "reliability", "params": {"analysis_type": "weibull", "times": [100, 200, 300], "status": [1, 1, 1]}}',
    },
    "multivariate": {
        "description": "Multivariate analysis: PCA, cluster, discriminant, correlation_matrix",
        "category": "multivariate",
        "input": ["analysis_type", "file", "columns", "values", "group_column", "method", "n_clusters", "n_components"],
        "output_fields": ["eigenvalues", "loadings", "clusters", "accuracy"],
        "example": '{"command": "multivariate", "params": {"analysis_type": "pca", "columns": ["x1", "x2", "x3"], "file": "data.csv"}}',
    },
    "timeseries": {
        "description": "Time series analysis: exponential smoothing, ARIMA, decomposition, ACF/PACF",
        "category": "advanced",
        "input": ["analysis_type", "values", "frequency", "order", "n_forecast"],
        "output_fields": ["analysis_type", "fitted_values", "forecast", "parameters"],
        "example": '{"command": "timeseries", "params": {"analysis_type": "exp_smoothing", "values": [10, 12, 11, 13, 14], "frequency": 4}}',
    },
    "power": {
        "description": "Power analysis and sample size calculation",
        "category": "hypothesis",
        "input": ["analysis_type", "effect_size", "alpha", "power", "n", "k_groups", "df"],
        "output_fields": ["analysis_type", "sample_size", "power", "effect_size"],
        "example": '{"command": "power", "params": {"analysis_type": "t_test", "effect_size": 0.5, "power": 0.80}}',
    },
    "clean": {
        "description": "Data cleaning: drop, impute_mean, impute_median, winsorize, clip",
        "category": "data",
        "input": ["values", "method"],
        "output_fields": ["method", "n_original", "n_clean", "n_removed", "before", "after"],
        "example": '{"command": "clean", "params": {"values": [...], "method": "impute_mean"}}',
    },
    "transform": {
        "description": "Data transformation: log, sqrt, boxcox, johnson, rank, standardize, recip",
        "category": "data",
        "input": ["values", "method"],
        "output_fields": ["method", "before", "after", "values"],
        "example": '{"command": "transform", "params": {"values": [...], "method": "boxcox"}}',
    },
    "report": {
        "description": "Generate comprehensive analysis report",
        "category": "report",
        "input": ["values", "usl", "lsl"],
        "output_fields": ["report_file", "analyses"],
        "example": '{"command": "report", "params": {"values": [...], "usl": 11.0, "lsl": 9.0}}',
    },
    "discover": {
        "description": "Discover available commands and their capabilities",
        "category": "data",
        "input": ["command_name", "category"],
        "output_fields": ["total_commands", "commands"],
        "example": '{"command": "discover"}',
    },
    "advanced": {
        "description": "Advanced statistical methods: mixed effects, Fisher's exact test, McNemar, Cochran's Q",
        "category": "advanced",
        "input": ["analysis_type", "groups", "group_ids", "observed", "data"],
        "output_fields": ["analysis_type", "p_value", "significant", "interpretation"],
        "example": '{"command": "advanced", "params": {"analysis_type": "exact_test", "observed": [[10, 5], [3, 12]]}}',
    },
    "run": {
        "description": "Run custom Python script with data",
        "category": "advanced",
        "input": ["script", "data"],
        "output_fields": ["result"],
        "example": '{"command": "run", "params": {"script": "result = sum(data[\'values\'])", "data": {"values": [1, 2, 3]}}}',
    },
}
