"""Command discovery metadata for AI agents."""

COMMANDS = {
    "explore": {
        "description": "Explore data file structure: columns, types, missing values, basic stats",
        "category": "data",
        "input": ["file", "sheet", "rows"],
        "params": [
            {"name": "file", "required": True, "type": "string", "desc": "Path to data file (xlsx, csv, json, txt)"},
            {"name": "sheet", "required": False, "type": "string", "desc": "Sheet name for Excel files"},
            {"name": "rows", "required": False, "type": "integer", "desc": "Number of rows to preview"},
        ],
        "output_fields": ["n_rows", "n_columns", "columns", "numeric_columns", "sample_data"],
        "example": '{"command": "explore", "params": {"file": "data.xlsx"}}',
    },
    "descriptive": {
        "description": "Descriptive statistics: mean, median, SD, RSD%, range, quartiles, 95% CI",
        "category": "basic",
        "input": ["values"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Numeric data values"},
        ],
        "output_fields": [
            "n",
            "mean",
            "median",
            "std",
            "rsd_percent",
            "min",
            "max",
            "range",
            "q1",
            "q3",
            "iqr",
            "ci_95_lower",
            "ci_95_upper",
            "skewness",
            "kurtosis",
        ],
        "example": '{"command": "descriptive", "params": {"values": [10.2, 10.5, 10.3]}}',
    },
    "normality": {
        "description": "Normality tests: Shapiro-Wilk, Anderson-Darling, Lilliefors",
        "category": "basic",
        "input": ["values"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Numeric data values (min 3)"},
        ],
        "output_fields": ["shapiro_wilk", "anderson_darling", "lilliefors", "is_normal"],
        "example": '{"command": "normality", "params": {"values": [10.2, 10.5, 10.3]}}',
    },
    "capability": {
        "description": "Process capability: Cp, Cpk, Pp, Ppk, Cpm, confidence intervals",
        "category": "spc",
        "input": ["values", "usl", "lsl", "target"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Process measurement data"},
            {"name": "usl", "required": True, "type": "number", "desc": "Upper specification limit"},
            {"name": "lsl", "required": True, "type": "number", "desc": "Lower specification limit"},
            {"name": "target", "required": False, "type": "number", "desc": "Target value (defaults to midpoint)"},
        ],
        "output_fields": [
            "cp",
            "cpk",
            "pp",
            "ppk",
            "cpm",
            "cp_ci_lower",
            "cp_ci_upper",
            "cpk_ci_lower",
            "cpk_ci_upper",
            "rating",
            "performance",
        ],
        "example": '{"command": "capability", "params": {"values": [10.1, 10.2, 10.0, 10.3], "usl": 11.0, "lsl": 9.0}}',
    },
    "control_chart": {
        "description": "Control charts: xbar, r, imr, p, np, c, u, ewma, cusum",
        "category": "spc",
        "input": ["values", "chart_type", "subgroup_size"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Process measurement data"},
            {"name": "chart_type", "required": True, "type": "string", "desc": "Chart type: xbar, r, imr, p, np, c, u, ewma, cusum"},
            {"name": "subgroup_size", "required": False, "type": "integer", "desc": "Subgroup size for xbar/r charts (default 5)"},
        ],
        "output_fields": ["chart_type", "center", "ucl", "lcl", "points", "out_of_control_points", "summary"],
        "example": '{"command": "control_chart", "params": {"chart_type": "imr", "values": [10.1, 10.2, 10.0, 10.3, 10.1]}}',
    },
    "ttest": {
        "description": "t-tests: one_sample, two_sample, paired",
        "category": "hypothesis",
        "input": ["test_type", "values", "values2", "mu"],
        "params": [
            {"name": "test_type", "required": True, "type": "string", "desc": "Test type: one_sample, two_sample, paired"},
            {"name": "values", "required": True, "type": "array", "desc": "First sample or only sample for one_sample"},
            {"name": "values2", "required": False, "type": "array", "desc": "Second sample (required for two_sample and paired)"},
            {"name": "mu", "required": False, "type": "number", "desc": "Hypothesized mean for one_sample test (default 0)"},
        ],
        "output_fields": ["test_type", "t_statistic", "p_value", "significant", "ci_95"],
        "example": '{"command": "ttest", "params": {"test_type": "two_sample", "values": [10.2, 10.5], "values2": [11.3, 11.5]}}',
    },
    "anova": {
        "description": "ANOVA: one_way, two_way",
        "category": "hypothesis",
        "input": ["anova_type", "groups", "alpha", "data"],
        "params": [
            {"name": "anova_type", "required": True, "type": "string", "desc": "ANOVA type: one_way, two_way"},
            {"name": "groups", "required": True, "type": "array", "desc": "List of groups, each group is an array of values"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level (default 0.05)"},
            {"name": "data", "required": False, "type": "object", "desc": "Data for two_way ANOVA with factor columns"},
        ],
        "output_fields": ["anova_type", "f_statistic", "p_value", "significant", "eta_squared", "omega_squared", "df_between", "df_within", "ss_between", "ss_within", "ms_between", "ms_within"],
        "example": '{"command": "anova", "params": {"anova_type": "one_way", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "regression": {
        "description": "Regression: linear, quadratic, polynomial, multiple, stepwise, logistic, exponential, power, logarithmic, sigmoid",
        "category": "regression",
        "input": ["x", "y", "reg_type", "degree", "file", "x_columns", "y_column", "alpha"],
        "params": [
            {"name": "x", "required": True, "type": "array", "desc": "Independent variable values (or list of arrays for multiple)"},
            {"name": "y", "required": True, "type": "array", "desc": "Dependent variable values"},
            {"name": "reg_type", "required": False, "type": "string", "desc": "Regression type (default linear): linear, quadratic, polynomial, multiple, stepwise, logistic, exponential, power, logarithmic, sigmoid"},
            {"name": "degree", "required": False, "type": "integer", "desc": "Polynomial degree (only for polynomial type)"},
            {"name": "file", "required": False, "type": "string", "desc": "Data file path (alternative to x/y arrays)"},
            {"name": "x_columns", "required": False, "type": "array", "desc": "Column names for X when using file input"},
            {"name": "y_column", "required": False, "type": "string", "desc": "Column name for Y when using file input"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level for stepwise (default 0.05)"},
        ],
        "output_fields": ["regression_type", "r_squared", "adj_r_squared", "coefficients", "f_statistic", "p_value"],
        "example": '{"command": "regression", "params": {"x": [1, 2, 3], "y": [2, 4, 6]}}',
    },
    "correlation": {
        "description": "Correlation: pearson, spearman, kendall",
        "category": "regression",
        "input": ["x", "y", "method"],
        "params": [
            {"name": "x", "required": True, "type": "array", "desc": "First variable values"},
            {"name": "y", "required": True, "type": "array", "desc": "Second variable values"},
            {"name": "method", "required": False, "type": "string", "desc": "Correlation method (default pearson): pearson, spearman, kendall"},
        ],
        "output_fields": ["method", "correlation", "p_value", "r_squared"],
        "example": '{"command": "correlation", "params": {"x": [1, 2, 3], "y": [2, 4, 6]}}',
    },
    "nonparametric": {
        "description": "Non-parametric tests: mann_whitney, kruskal_wallis, wilcoxon, chi_square, friedman",
        "category": "hypothesis",
        "input": ["test_type", "x", "y", "groups", "observed"],
        "params": [
            {"name": "test_type", "required": True, "type": "string", "desc": "Test type: mann_whitney, kruskal_wallis, wilcoxon, chi_square, friedman"},
            {"name": "x", "required": False, "type": "array", "desc": "First sample (mann_whitney, wilcoxon)"},
            {"name": "y", "required": False, "type": "array", "desc": "Second sample (mann_whitney, wilcoxon)"},
            {"name": "groups", "required": False, "type": "array", "desc": "List of groups (kruskal_wallis, friedman)"},
            {"name": "observed", "required": False, "type": "array", "desc": "Observed frequency table (chi_square)"},
        ],
        "output_fields": ["test_type", "statistic", "p_value", "significant"],
        "example": '{"command": "nonparametric", "params": {"test_type": "mann_whitney", "x": [10.2, 10.5], "y": [11.3, 11.5]}}',
    },
    "homogeneity": {
        "description": "Homogeneity of variance: levene, bartlett",
        "category": "hypothesis",
        "input": ["test_type", "groups"],
        "params": [
            {"name": "test_type", "required": True, "type": "string", "desc": "Test type: levene, bartlett"},
            {"name": "groups", "required": True, "type": "array", "desc": "List of groups, each group is an array of values"},
        ],
        "output_fields": ["test_type", "statistic", "p_value", "significant"],
        "example": '{"command": "homogeneity", "params": {"test_type": "levene", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "multiple_comparison": {
        "description": "Multiple comparison: tukey, bonferroni, scheffe",
        "category": "hypothesis",
        "input": ["test_type", "groups", "alpha"],
        "params": [
            {"name": "test_type", "required": True, "type": "string", "desc": "Test type: tukey, bonferroni, scheffe"},
            {"name": "groups", "required": True, "type": "array", "desc": "List of groups, each group is an array of values"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level (default 0.05)"},
        ],
        "output_fields": ["test_type", "comparisons", "significant_pairs"],
        "example": '{"command": "multiple_comparison", "params": {"test_type": "tukey", "groups": [[10.2, 10.5], [11.3, 11.5]]}}',
    },
    "equivalence": {
        "description": "Equivalence tests: tost, one_sample_tost",
        "category": "hypothesis",
        "input": ["test_type", "values", "values2", "mu", "delta"],
        "params": [
            {"name": "test_type", "required": True, "type": "string", "desc": "Test type: tost, one_sample_tost"},
            {"name": "values", "required": True, "type": "array", "desc": "First sample values"},
            {"name": "values2", "required": False, "type": "array", "desc": "Second sample (required for tost)"},
            {"name": "mu", "required": False, "type": "number", "desc": "Reference mean for one_sample_tost"},
            {"name": "delta", "required": True, "type": "number", "desc": "Equivalence margin"},
        ],
        "output_fields": ["test_type", "t_statistic", "p_value", "equivalent", "ci_90"],
        "example": '{"command": "equivalence", "params": {"test_type": "tost", "values": [10.2, 10.5], "values2": [10.3, 10.6], "delta": 0.5}}',
    },
    "outlier": {
        "description": "Outlier detection: grubbs, dixon, iqr, zscore",
        "category": "basic",
        "input": ["values", "method", "alpha"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Numeric data values"},
            {"name": "method", "required": False, "type": "string", "desc": "Detection method (default grubbs): grubbs, dixon, iqr, zscore"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level (default 0.05)"},
        ],
        "output_fields": ["method", "outliers", "n_outliers", "clean_data"],
        "example": '{"command": "outlier", "params": {"values": [10, 11, 10, 12, 100], "method": "grubbs"}}',
    },
    "trend": {
        "description": "Trend analysis: cusum, ewma, runs",
        "category": "spc",
        "input": ["values", "test_type", "target"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Process measurement data"},
            {"name": "test_type", "required": False, "type": "string", "desc": "Test type (default cusum): cusum, ewma, runs"},
            {"name": "target", "required": False, "type": "number", "desc": "Target value (default: mean of values)"},
        ],
        "output_fields": ["test_type", "alarm_points", "stable"],
        "example": '{"command": "trend", "params": {"values": [10.1, 10.2, 10.0, 10.3, 10.1], "test_type": "cusum"}}',
    },
    "doe": {
        "description": "Design of Experiments: full_factorial, fractional_factorial, response_surface, taguchi",
        "category": "doe",
        "input": ["doe_type", "factors"],
        "params": [
            {"name": "doe_type", "required": True, "type": "string", "desc": "DOE type: full_factorial, fractional_factorial, response_surface, taguchi"},
            {"name": "factors", "required": True, "type": "array", "desc": "Factor definitions: [{name, levels}] or [{name, low, high}]"},
        ],
        "output_fields": ["doe_type", "design_matrix", "n_runs"],
        "example": '{"command": "doe", "params": {"doe_type": "full_factorial", "factors": [{"name": "Temp", "levels": 3}, {"name": "Time", "levels": 2}]}}',
    },
    "gage_rr": {
        "description": "MSA/Gage R&R: crossed, nested, attribute, bias, linearity, stability",
        "category": "msa",
        "input": ["analysis_type", "measurements", "parts", "operators", "tolerance"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: crossed, nested, attribute, bias, linearity, stability"},
            {"name": "measurements", "required": True, "type": "array", "desc": "Measurement data (2D array or flat array)"},
            {"name": "parts", "required": True, "type": "array", "desc": "Part identifiers for each measurement"},
            {"name": "operators", "required": True, "type": "array", "desc": "Operator identifiers for each measurement"},
            {"name": "tolerance", "required": False, "type": "number", "desc": "Tolerance width for % study variation"},
        ],
        "output_fields": ["analysis_type", "variance_components", "contribution", "study_variation", "ndc", "rating"],
        "example": '{"command": "gage_rr", "params": {"analysis_type": "crossed", "measurements": [[10,11,10],[11,12,11]], "parts": ["P1","P2"], "operators": ["A","A"]}}',
    },
    "reliability": {
        "description": "Reliability and survival analysis: weibull, kaplan_meier, distribution, stability",
        "category": "reliability",
        "input": ["analysis_type", "times", "status", "values"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: weibull, kaplan_meier, distribution, stability"},
            {"name": "times", "required": False, "type": "array", "desc": "Failure/censor times (required for weibull, kaplan_meier)"},
            {"name": "status", "required": False, "type": "array", "desc": "Event status: 1=failure, 0=censored (required for weibull, kaplan_meier)"},
            {"name": "values", "required": False, "type": "array", "desc": "Data values (required for distribution, stability)"},
        ],
        "output_fields": ["parameters", "b_lives", "mttf", "shelf_life"],
        "example": '{"command": "reliability", "params": {"analysis_type": "weibull", "times": [100, 200, 300], "status": [1, 1, 1]}}',
    },
    "multivariate": {
        "description": "Multivariate analysis: PCA, cluster, discriminant, correlation_matrix",
        "category": "multivariate",
        "input": ["analysis_type", "file", "columns", "values", "group_column", "method", "n_clusters", "n_components"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: pca, cluster, discriminant, correlation_matrix"},
            {"name": "file", "required": False, "type": "string", "desc": "Data file path"},
            {"name": "columns", "required": False, "type": "array", "desc": "Column names to include"},
            {"name": "values", "required": False, "type": "array", "desc": "Data as 2D array (alternative to file)"},
            {"name": "group_column", "required": False, "type": "string", "desc": "Group column for discriminant analysis"},
            {"name": "method", "required": False, "type": "string", "desc": "Clustering method (default kmeans): kmeans, hierarchical"},
            {"name": "n_clusters", "required": False, "type": "integer", "desc": "Number of clusters (default 3)"},
            {"name": "n_components", "required": False, "type": "integer", "desc": "Number of PCA components"},
        ],
        "output_fields": ["eigenvalues", "loadings", "clusters", "accuracy"],
        "example": '{"command": "multivariate", "params": {"analysis_type": "pca", "columns": ["x1", "x2", "x3"], "file": "data.csv"}}',
    },
    "timeseries": {
        "description": "Time series analysis: exponential smoothing, ARIMA, decomposition, ACF/PACF",
        "category": "advanced",
        "input": ["analysis_type", "values", "frequency", "order", "n_forecast"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: exp_smoothing, arima, decomposition, acf"},
            {"name": "values", "required": True, "type": "array", "desc": "Time series data values"},
            {"name": "frequency", "required": False, "type": "integer", "desc": "Seasonal period (default 4 for quarterly, 12 for monthly)"},
            {"name": "order", "required": False, "type": "array", "desc": "ARIMA order [p, d, q] (default [1,1,1])"},
            {"name": "n_forecast", "required": False, "type": "integer", "desc": "Number of periods to forecast (default 5)"},
        ],
        "output_fields": ["analysis_type", "fitted_values", "forecast", "parameters"],
        "example": '{"command": "timeseries", "params": {"analysis_type": "exp_smoothing", "values": [10, 12, 11, 13, 14], "frequency": 4}}',
    },
    "power": {
        "description": "Power analysis and sample size calculation",
        "category": "hypothesis",
        "input": ["analysis_type", "effect_size", "alpha", "power", "n", "k_groups", "df"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: t_test, anova, proportion, correlation"},
            {"name": "effect_size", "required": False, "type": "number", "desc": "Effect size (Cohen's d, f, r, or h)"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level (default 0.05)"},
            {"name": "power", "required": False, "type": "number", "desc": "Desired power (default 0.80). Provide 2 of: effect_size, power, n"},
            {"name": "n", "required": False, "type": "integer", "desc": "Sample size per group. Provide 2 of: effect_size, power, n"},
            {"name": "k_groups", "required": False, "type": "integer", "desc": "Number of groups for ANOVA (default 2)"},
            {"name": "df", "required": False, "type": "integer", "desc": "Degrees of freedom for correlation test"},
        ],
        "output_fields": ["analysis_type", "sample_size", "power", "effect_size"],
        "example": '{"command": "power", "params": {"analysis_type": "t_test", "effect_size": 0.5, "power": 0.80}}',
    },
    "clean": {
        "description": "Data cleaning: drop, impute_mean, impute_median, winsorize, clip",
        "category": "data",
        "input": ["values", "method"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Data values (may contain NaN/Inf)"},
            {"name": "method", "required": False, "type": "string", "desc": "Cleaning method (default drop): drop, impute_mean, impute_median, winsorize, clip"},
        ],
        "output_fields": ["method", "n_original", "n_clean", "n_removed", "before", "after"],
        "example": '{"command": "clean", "params": {"values": [1, 2, null, 4], "method": "impute_mean"}}',
    },
    "transform": {
        "description": "Data transformation: log, sqrt, boxcox, johnson, rank, standardize, recip",
        "category": "data",
        "input": ["values", "method"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Numeric data values"},
            {"name": "method", "required": False, "type": "string", "desc": "Transform method (default log): log, sqrt, boxcox, johnson, rank, standardize, recip"},
        ],
        "output_fields": ["method", "before", "after", "values"],
        "example": '{"command": "transform", "params": {"values": [1, 2, 3, 4, 5], "method": "boxcox"}}',
    },
    "report": {
        "description": "Generate comprehensive analysis report",
        "category": "report",
        "input": ["values", "usl", "lsl"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Numeric data values"},
            {"name": "usl", "required": False, "type": "number", "desc": "Upper specification limit"},
            {"name": "lsl", "required": False, "type": "number", "desc": "Lower specification limit"},
        ],
        "output_fields": ["report_file", "analyses"],
        "example": '{"command": "report", "params": {"values": [10.1, 10.2, 10.0, 10.3], "usl": 11.0, "lsl": 9.0}}',
    },
    "discover": {
        "description": "Discover available commands and their capabilities",
        "category": "data",
        "input": ["command_name", "category"],
        "params": [
            {"name": "command_name", "required": False, "type": "string", "desc": "Get full details for a specific command"},
            {"name": "category", "required": False, "type": "string", "desc": "Filter by category: data, basic, spc, hypothesis, regression, doe, msa, reliability, multivariate, advanced, workflow, report"},
        ],
        "output_fields": ["total_commands", "commands"],
        "example": '{"command": "discover"}',
    },
    "advanced": {
        "description": "Advanced statistical methods: mixed effects, Fisher's exact test, McNemar, Cochran's Q",
        "category": "advanced",
        "input": ["analysis_type", "groups", "group_ids", "observed", "data"],
        "params": [
            {"name": "analysis_type", "required": True, "type": "string", "desc": "Analysis type: exact_test, mcnemar, cochran_q, mixed_effects"},
            {"name": "groups", "required": False, "type": "array", "desc": "Group data arrays"},
            {"name": "group_ids", "required": False, "type": "array", "desc": "Group identifiers for mixed_effects"},
            {"name": "observed", "required": False, "type": "array", "desc": "2x2 contingency table (exact_test, mcnemar)"},
            {"name": "data", "required": False, "type": "object", "desc": "Data dict for mixed_effects"},
        ],
        "output_fields": ["analysis_type", "p_value", "significant", "interpretation"],
        "example": '{"command": "advanced", "params": {"analysis_type": "exact_test", "observed": [[10, 5], [3, 12]]}}',
    },
    "run": {
        "description": "Run custom Python script with data",
        "category": "advanced",
        "input": ["script", "data"],
        "params": [
            {"name": "script", "required": True, "type": "string", "desc": "Python script to execute. Access data via 'data' dict. Set 'result' variable for output."},
            {"name": "data", "required": False, "type": "object", "desc": "Data dictionary accessible in script"},
        ],
        "output_fields": ["result"],
        "example": '{"command": "run", "params": {"script": "result = sum(data[\'values\'])", "data": {"values": [1, 2, 3]}}}',
    },
    "workflow": {
        "description": "Execute multi-step statistical workflow with automatic assumption checking",
        "category": "workflow",
        "input": ["steps", "values", "file", "auto_check", "alpha"],
        "params": [
            {"name": "steps", "required": True, "type": "array", "desc": "List of step objects: [{command, params?}]"},
            {"name": "values", "required": False, "type": "array", "desc": "Data values shared across all steps"},
            {"name": "file", "required": False, "type": "string", "desc": "Data file path (alternative to values)"},
            {"name": "auto_check", "required": False, "type": "boolean", "desc": "Auto-check assumptions between steps (default false)"},
            {"name": "alpha", "required": False, "type": "number", "desc": "Significance level for assumption checks (default 0.05)"},
        ],
        "output_fields": ["n_steps", "steps_results", "assumptions", "recommendations", "warnings", "summary"],
        "example": '{"command": "workflow", "params": {"steps": [{"command": "descriptive"}, {"command": "normality"}], "values": [10.2, 10.5, 10.3]}}',
    },
    "check_assumptions": {
        "description": "Check statistical assumptions for planned analysis and get recommendations",
        "category": "workflow",
        "input": ["values", "test_type", "values2", "groups"],
        "params": [
            {"name": "values", "required": True, "type": "array", "desc": "Data values to check"},
            {"name": "test_type", "required": True, "type": "string", "desc": "Planned test: ttest, anova, regression, correlation"},
            {"name": "values2", "required": False, "type": "array", "desc": "Second sample for two-sample tests"},
            {"name": "groups", "required": False, "type": "array", "desc": "Groups for ANOVA"},
        ],
        "output_fields": ["assumptions", "recommendations", "overall_assumptions_met"],
        "example": '{"command": "check_assumptions", "params": {"values": [10.2, 10.5, 10.3], "test_type": "ttest"}}',
    },
    "recommend": {
        "description": "Get recommended statistical tests based on data description and analysis goal",
        "category": "workflow",
        "input": ["goal", "n_groups", "paired", "n_variables", "outcome_type"],
        "params": [
            {"name": "goal", "required": True, "type": "string", "desc": "Analysis goal: compare, relationship, predict, monitor"},
            {"name": "n_groups", "required": False, "type": "integer", "desc": "Number of groups (default 2)"},
            {"name": "paired", "required": False, "type": "boolean", "desc": "Whether samples are paired (default false)"},
            {"name": "n_variables", "required": False, "type": "integer", "desc": "Number of variables (default 1)"},
            {"name": "outcome_type", "required": False, "type": "string", "desc": "Outcome type: continuous, categorical (default continuous)"},
        ],
        "output_fields": ["recommendations", "top_recommendation"],
        "example": '{"command": "recommend", "params": {"goal": "compare", "n_groups": 2}}',
    },
    "workflow_template": {
        "description": "Execute predefined workflow templates: manufacturing, comparison, capability, exploration, reliability, doe, timeseries, regression, multivariate",
        "category": "workflow",
        "input": ["template_name", "values", "usl", "lsl", "target", "values2", "groups", "paired", "times", "status", "factors", "responses", "frequency", "n_forecast", "x", "y", "reg_type", "n_components", "n_clusters"],
        "params": [
            {"name": "template_name", "required": True, "type": "string", "desc": "Template: manufacturing, comparison, capability, exploration, reliability, doe, timeseries, regression, multivariate"},
            {"name": "values", "required": False, "type": "array", "desc": "Primary data values"},
            {"name": "usl", "required": False, "type": "number", "desc": "Upper specification limit"},
            {"name": "lsl", "required": False, "type": "number", "desc": "Lower specification limit"},
            {"name": "target", "required": False, "type": "number", "desc": "Target value"},
            {"name": "values2", "required": False, "type": "array", "desc": "Second sample for comparison template"},
            {"name": "groups", "required": False, "type": "array", "desc": "Groups for comparison template"},
            {"name": "paired", "required": False, "type": "boolean", "desc": "Whether samples are paired"},
            {"name": "times", "required": False, "type": "array", "desc": "Failure/censor times for reliability template"},
            {"name": "status", "required": False, "type": "array", "desc": "Event status for reliability template"},
            {"name": "factors", "required": False, "type": "array", "desc": "Factor definitions for doe template"},
            {"name": "responses", "required": False, "type": "array", "desc": "Response values for doe template"},
            {"name": "frequency", "required": False, "type": "integer", "desc": "Seasonal period for timeseries template"},
            {"name": "n_forecast", "required": False, "type": "integer", "desc": "Forecast periods for timeseries template"},
            {"name": "x", "required": False, "type": "array", "desc": "Independent variable for regression template"},
            {"name": "y", "required": False, "type": "array", "desc": "Dependent variable for regression template"},
            {"name": "reg_type", "required": False, "type": "string", "desc": "Regression type for regression template"},
            {"name": "n_components", "required": False, "type": "integer", "desc": "PCA components for multivariate template"},
            {"name": "n_clusters", "required": False, "type": "integer", "desc": "Cluster count for multivariate template"},
        ],
        "output_fields": ["n_steps", "steps_results", "assumptions", "recommendations", "warnings", "summary"],
        "example": '{"command": "workflow_template", "params": {"template_name": "manufacturing", "values": [10.2, 10.5, 10.3], "usl": 11.0, "lsl": 9.0}}',
    },
    "export_excel": {
        "description": "Export analysis report to Excel format",
        "category": "report",
        "input": ["report_data", "output_path"],
        "params": [
            {"name": "report_data", "required": True, "type": "object", "desc": "Report data from report() command"},
            {"name": "output_path", "required": True, "type": "string", "desc": "Output file path (.xlsx)"},
        ],
        "output_fields": ["format", "output_path", "file_size", "sheets"],
        "example": '{"command": "export_excel", "params": {"report_data": {"summary": {}}, "output_path": "report.xlsx"}}',
    },
    "export_pdf": {
        "description": "Export analysis report to PDF format",
        "category": "report",
        "input": ["report_data", "output_path"],
        "params": [
            {"name": "report_data", "required": True, "type": "object", "desc": "Report data from report() command"},
            {"name": "output_path", "required": True, "type": "string", "desc": "Output file path (.pdf)"},
        ],
        "output_fields": ["format", "output_path", "file_size"],
        "example": '{"command": "export_pdf", "params": {"report_data": {"summary": {}}, "output_path": "report.pdf"}}',
    },
}
